version: "3.3"

services:
  dsbpa:
    image: meetveracity/coding-challenge-app
    build: 
      context: .
    environment:
      - DSBPA_TEST_USER=dsbpa
      - DSBPA_TEST_PASSWORD=dsbpa
    ports:
      - "8080:8080"
  
  postgres:
    image: library/postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=dsbpa
      - POSTGRES_USER=dsbpa
      - POSTGRES_DB=dsbpa_test
    ports:
      - "5432:5432"